<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Part of Speech and the Semantic Contribution of Reduplication</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ReduplicationProjectWriteup_files/libs/clipboard/clipboard.min.js"></script>
<script src="ReduplicationProjectWriteup_files/libs/quarto-html/quarto.js"></script>
<script src="ReduplicationProjectWriteup_files/libs/quarto-html/popper.min.js"></script>
<script src="ReduplicationProjectWriteup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ReduplicationProjectWriteup_files/libs/quarto-html/anchor.min.js"></script>
<link href="ReduplicationProjectWriteup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ReduplicationProjectWriteup_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ReduplicationProjectWriteup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ReduplicationProjectWriteup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ReduplicationProjectWriteup_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Part of Speech and the Semantic Contribution of Reduplication</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Authors</div>
      <div class="quarto-title-meta-contents">
               <p>Alex Duchnowski </p>
               <p>Arushi Kalpande </p>
               <p>Ford Rowe </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>For the full code and data used in this paper, please visit our <a href="https://github.com/AlexDuchnowski/Reduplication">GitHub repository</a>.</p>
<section id="background-and-context" class="level1">
<h1>1 Background and Context</h1>
<p>The repetition of a morpheme, word, or phrase, also known as reduplication, has a variety of uses in the world’s languages. When looking at the behavior of English reduplication, we see that its scope is fairly limited in terms of its semantic effects, lacking a productivity that is found in partial or total reduplication found in other languages (Harada 2007). This does not mean that analyzing English reduplication is not worthwhile, and as will be discussed later in this paper, there are still unanswered questions relating to the mechanical properties of reduplication. In fact, the impetus for the research seen here was derived from a casual in-the-wild observation made by this paper’s authors, in which they observed that while both of the following tokens involve the apparently identical morphological process of reduplication, the semantic behavior of “run run” (as opposed to telling someone just to “run”) and “<a href="https://www.youtube.com/watch?v=m2L-Sa_6MU0&amp;t=65s">blackmail blackmail</a>” (as opposed to emotional blackmail) contained a subtle difference. In the former, the reduplication seemed to be contributing some form of emphasis or intensity, while in the latter the reduplication seemed to be pointing towards the blackmail being real or normal, as opposed to a more specific or non-standard type of blackmail. This paper, in addition to the goals outlined in Section 1.3, seeks to identify whether or not the differing part-of-speech of the base forms is predictive of the differing semantic behavior of their reduplicated forms.</p>
<section id="contrastive-reduplication" class="level2">
<h2 class="anchored" data-anchor-id="contrastive-reduplication">1.1 Contrastive Reduplication</h2>
<p>The specific phenomenon that will be examined in this paper is Contrastive Focus Reduplication, also simply called Contrastive Reduplication (CR), which is a type of morphological process in English that is used to contrast the meaning of the reduplicated form with the meaning of its non-reduplicated base, which may be explicit or implied within the context of an utterance.</p>
<p>As a result of limiting our scope in this way, our research will not be a comprehensive analysis of all semantic behavior of all types of English reduplication. This means that excluded from our analysis will be reduplicated forms such as baby talk (eg. goo-goo, ga-ga); deprecative reduplication, which is used in the depreciation or devaluation of the base form (eg. party-schmarty, vegetables-schmegetables); intensive reduplication, which is used to non-contrastively intensify the meaning of the base form (eg. triplication in “It’s all about money, money, money!”); and others as outlined in the typological work of Ghomeshi et al.&nbsp;(2004).</p>
<p>Additionally, there are some forms of reduplication which may fall under the scope of CR, but whose semantic content is not variable in such a way as to be relevant to the research conducted here. Drawing upon the work of Widlitzki (2016), our investigation into CR will be limited to context-dependent reduplication, in which the meaning of the reduplicated form is somewhat dependent upon the context in which it is uttered. By this measure, we will be excluding CR which falls under the umbrella of having a <em>single default meaning</em> or an <em>emerging default meaning</em>. The former refers to CR which has a broadly recognized meaning that is not dependent upon context, such as “really-really” or “very-very.” The latter refers to CR forms which are seemingly in the process of developing a conventionalized meaning, such as the increasingly salient romantic connotation of the phrase “like-like.”</p>
</section>
<section id="semantic-contribution" class="level2">
<h2 class="anchored" data-anchor-id="semantic-contribution">1.2 Semantic Contribution</h2>
<p>Having established the scope of CR that we will be dealing with in this paper, we’ll now turn to elaborating on what we mean when we refer to the ‘semantic contribution’ of reduplication. Put simply, we are referring to the way in which the meaning of the reduplicated word or phrase changes for having undergone the morphological process of reduplication. The following is a three-way typology that we have developed to facilitate the distinction of the different semantic contributions of CR, based primarily on prior work by Ghomeshi et al.&nbsp;(2004) and Widlitzki (2016). Most relevantly, from Ghomeshi et al.&nbsp;(2004:343) we take the categories <em>Prototypical</em>, <em>Extreme</em>, and <em>Salient</em> to be the three major types of meanings conveyed by CR.</p>
<section id="prototypical" class="level3">
<h3 class="anchored" data-anchor-id="prototypical">Prototypical</h3>
<p>CR which is prototypical is used to contrast a real, typical, or standard example with an example that is not understood to be so. This is what is most commonly understood to be the effect of English contrastive reduplication, and, as we will see later in the paper, is the most commonly occurring type. Examples of Prototypical CR (PCR) would be the following:</p>
<blockquote class="blockquote">
<ol type="1">
<li>I’ll make the tuna salad, and you make the SALAD-salad.<br>
</li>
<li>Here’s the skinny. We dressmakers have a very strict code, so I need to know, do you deserve to wear virginal white? Because if you don’t, you’ll have to wear an off-white, what we call a hussy white. So which will it be, WHITE-white?</li>
</ol>
</blockquote>
<p>In (1), the salad being described as the “salad-salad” is most likely a leafy green salad that may be referred to as the ‘prototypical’ version of a salad. In being brought to contrast with a tuna salad, a less ‘prototypical’ type of salad than a leafy green salad, (1) demonstrates an example of PCR. In (2), the color “white-white” refers to the former “virginal” white. The speaker is using reduplication to draw a distinction between pure white and off-white, which is not white-white, thus (2) is also representative of the use of PCR.</p>
</section>
<section id="extreme" class="level3">
<h3 class="anchored" data-anchor-id="extreme">Extreme</h3>
<p>CR which is extreme is used to indicate an intensified meaning, most straightforwardly comparable to saying that something is “very/extremely/super X.” Examples of Extreme CR (ECR) would be the following:</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>A [to B, who is about to give a recital]: Are you nervous? <br>B: Yeah, but, you know, not NERVOUS-nervous.<br>
</li>
<li>First of all, I’m not like a CELEBRITY-celebrity; I don’t get recognized when I’m walking down the street.</li>
</ol>
</blockquote>
<p>In (3), Speaker B is contrasting their level of nervousness on a gradable scale, wherein they are asserting that they are just nervous (i.e., a ‘little’ nervous) as opposed to “nervous-nervous” (i.e., ‘very’ nervous), thus demonstrating a use of ECR. In (4), the speaker is drawing a contrast between different levels of celebrity, arguing that they are only a celebrity to a certain degree, as opposed to celebrities who are of a higher caliber. In this way (4) is an example of ECR by way of the speaker’s assertion that they are not an extreme version of their occupation.</p>
</section>
<section id="salient" class="level3">
<h3 class="anchored" data-anchor-id="salient">Salient</h3>
<p>CR which is salient is used to indicate that there is a contextually salient or accessible sense or reference for the meaning of the reduplicated form. This is different from the above two types of CR, which are both contextually-dependent in their own way, by being inclusive of grammatical categories such as proper nouns, and word types such as indexicals, whose referents change at the level of the utterance rather than the sentence. Examples of Salient CR (SCR) would be the following:</p>
<blockquote class="blockquote">
<ol start="5" type="1">
<li>A: Did you check out the leak in the bathroom? <br>B: What leak? <br>A: The LEAK-leak. [drags her into the bathroom]<br>
</li>
<li>We have a wonderful bed. I think you’ll enjoy it. Not ENJOY-enjoy. Sleep. Enjoyable sleep.</li>
<li>They just call him psycho-Marcus because they’re trying to distinguish between him and MARCUS-Marcus and normal-Marcus.</li>
</ol>
</blockquote>
<p>In (5), Speaker A is employing contrastive reduplication in order to assert that the leak they are referring to is not some generalized leak out in the world, but is rather a specific leak whose referent should be accessible to Speaker B in the conversational context. Because we are not participating in the conversation between Speakers A and B, unlike the meanings of the CR present in (1-4), the meaning of (5) is left slightly unclear due to the highly contextually salient nature of SCR.</p>
<p>(6) is representative of SCR where it applies to the contrast between a metaphorical and literal reading of the base form. The speaker is using “enjoy-enjoy” to refer to a meaning that contains innuendo, which is a nonstandard reading of “enjoy” that is only accessible in the utterance as a result of their mentioning the bed in the prior sentence. In this way, the meaning of “enjoy-enjoy” arises due to its salience in the context of its utterance, and thus we can classify (6) as an instance of SCR.</p>
<p>Finally we have chosen to classify tokens like the one that appears in (7) as SCR for a reason much similar to (5), in that proper nouns behave in such a way as to ‘pick out’ specific contextually salient individuals, and thus CR may be used to differentiate between two or more similarly-named people. This is the case in (7), where the speaker is using “Marcus-Marcus” to mean something along the lines of “the Marcus that we know” or “the Marcus that isn’t the other two Marcuses that we know,” and so we can refer to this type of reduplication as SCR.</p>
</section>
</section>
<section id="the-task-at-hand" class="level2">
<h2 class="anchored" data-anchor-id="the-task-at-hand">1.3 The Task at Hand</h2>
<p>In this paper, we will ask whether the part of speech (POS) of a reduplicated form influences its semantic contribution in the context of its utterance. We investigate this question by annotating and analyzing two English-language corpora. It is our hypothesis that we will see a distinct trend in certain parts of speech being more commonly Prototypical/Extreme/Salient than others, such as scalar adjectives trending extreme or nouns being prototypical.</p>
<p>This question is of value in that English reduplication is rare and often taken to be a purely prototypical process, but as we will see both in our discussion of existing research and in our analysis of our own data, this is not necessarily the case. In related research (Ghomeshi et al., 2004; Widlitzki, 2016) we find acknowledgements of CR outside of the scope of purely prototypical contrast, but the underlying cause for this observed semantic variation in CR has not been elaborated upon to the degree that we will be exploring it in this paper. Insofar as the existing literature is concerned, the motivating factor in the semantic variation of CR forms is currently unclear. Furthermore, since reduplication has multiple subtly distinct effects, our hypothesis is based on the intuition that looking at the type of content being reduplicated might shed light on why the resulting semantic effects differ.</p>
</section>
</section>
<section id="data" class="level1">
<h1>2 Data</h1>
<section id="salad-salad-corpus" class="level2">
<h2 class="anchored" data-anchor-id="salad-salad-corpus">2.1 Salad-Salad Corpus</h2>
<p>The majority of our confirmed instances of CR are taken from what we will be referring to in this paper as the Salad-Salad Corpus, which consists of the examples and data used in Ghomeshi et al.&nbsp;(2004). All listed entries in this corpus were annotated as instances of contrastive reduplication as a part of their work, thus providing us with a robust base of data upon which to test our hypothesis. The Salad-Salad Corpus was last updated on May 30, 2014, and contains 334 entries along with their source, context, and full quotation. The corpus also contains an index of POS and source medium, as well as other notations such as whether or not the reduplicated form involved repeating the inflectional morphology of a given token.</p>
</section>
<section id="opensubtitles-corpus" class="level2">
<h2 class="anchored" data-anchor-id="opensubtitles-corpus">2.2 OpenSubtitles Corpus</h2>
<p>In addition to the Salad-Salad Corpus, we drew upon a sample of a 2018 OpenSubtitles Corpus containing about 222,000 sentences (1.38 million tokens). OpenSubtitles is an online database of subtitles in various languages for movies and TV shows; users upload their transcriptions, which are then shared publicly and downloadable for free. At time of writing, the site contains 7,124,730 subtitle entries. We accessed this corpus through <a href="https://opus.nlpl.eu/OpenSubtitles/en&amp;/v2018/OpenSubtitles">OPUS</a>, an online database of 1,210 corpora across 744 languages.</p>
<p>The OpenSubtitles Corpus that we selected is constrained to English-language subtitles only, is drawn from a variety of genres and periods, and includes both live-action and animated content. Our sample of this corpus, which will be elaborated upon in the following section, consisted of 613 examples which were then manually checked for CR.</p>
</section>
</section>
<section id="methodology" class="level1">
<h1>3 Methodology</h1>
<section id="preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing">3.1 Preprocessing</h2>
<p>When processing both corpora, we limited our focus to the four parts of speech which most often undergo reduplication in English: Nouns, Verbs, Adjectives, and Adverbs (Widlitzki, 2016). The Salad-Salad Corpus required minimal filtering beyond this, as these entries were already confirmed to be CR by Ghomeshi et al.&nbsp;(2004) and were already annotated for their POS in the corpus’s index. Apart from filtering for the four POS’s of interest, we also removed instances of reduplicated “like”, as this has an emerging default meaning (as noted in section 1.1).</p>
<p>Our pre-processing work on the OpenSubtitles corpus was significantly more intensive, as we needed to filter for repetition of words while retaining relevant context for each example and filtering out repetition which was unlikely to be CR. We started by transforming the initial corpus so that every line contained copies of the lines surrounding it for context. The initial filtering of this content was then achieved with the following Linux script (for full context, see <a href="https://github.com/AlexDuchnowski/Reduplication/blob/main/scripts/extract_contextualized_redups.sh">this file</a>):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{bash}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> data/<span class="va">$name</span>/contextualized_<span class="va">$name</span>.txt                 <span class="kw">|</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span> <span class="at">-vP</span> <span class="st">'^[^\t]*\b([a-z]{3,})[ ,-]+\1[ ,-]+\1\b'</span>       <span class="kw">|</span>   <span class="co"># remove rows with triples in the first column</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="at">-re</span> <span class="st">'s/^([^\t]*)([[\(].*[]\)])(.*)\2/\1\3/g'</span>        <span class="kw">|</span>   <span class="co"># remove bracketed content in the first column</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="at">-re</span> <span class="st">'s/^([^\t]*)/\L\1/'</span>                             <span class="kw">|</span>   <span class="co"># convert text in the first column to lowercase</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">egrep</span> <span class="st">"^[^</span><span class="va">$tab</span><span class="st">]*\b([a-z]{3,})[ ,-]\1\b"</span>                 <span class="kw">|</span>   <span class="co"># filter for reduplications in the first column</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="at">-re</span> <span class="st">'s/^[^\t]*\b([a-z]{3,})[ ,-]\1\b[^\t]*\t/\1\t/g'</span>   <span class="kw">`</span><span class="co"># extract reduplicated words in the first column</span><span class="kw">`</span> <span class="dt">\</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="op">&gt;</span> data/<span class="va">$name</span>/<span class="va">${name}</span>_redups.txt</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As can be seen in the code above, we removed bracketed content since this was typically used to denote scene descriptions, sound effects, or other non-dialogue information. We also converted the column of interest to lowercase to facilitate searching for reduplication without case-sensitivity. Additionally, we removed instances of repetition where a word or morpheme was used more than twice in a row, as this was often singing or laughter, rather than actually reduplication. After these filters were applied, we searched for and extracted examples where a single word at least three letters in length was repeated (with a space, comma, or hyphen separating the two copies). The length requirement was to filter for more contentful words and to preemptively remove words in other POS categories such as prepositions and pronouns. Part of speech was then labeled using the POS tokenizer of the <code>spaCy</code> Python package, and these POS annotations were then used to filter for the four most commonly reduplicated parts of speech, in keeping with the filtering described for our Salad-Salad Corpus data. Applying this filter to about 222,000 lines of subtitles resulted in 613 candidate examples of CR.</p>
</section>
<section id="manual-annotation" class="level2">
<h2 class="anchored" data-anchor-id="manual-annotation">3.2 Manual Annotation</h2>
<section id="salad-salad" class="level3">
<h3 class="anchored" data-anchor-id="salad-salad">Salad-Salad</h3>
<p>Our resulting list was 286 entries long, down from the original 334, and was not entirely free of non-CR tokens. For example, an entry in which Jay Leno makes a joke about going to prison within a prison — “prison-prison” — was notated by the original authors as CR, but we agreed that this did not seem to be an accurate notation. In addition to verifying the presence of reduplication, we manually annotated whether or not the semantic contribution of the reduplication was Prototypical, Extreme, or Salient. We divided our annotation into two sessions, starting with the first 100 examples, then meeting to go over our answers and discuss any discrepancies before proceeding to annotate the rest. When we disagreed on an example, we would discuss the reasoning behind our annotations and then revise our judgements to produce a single label for each example. This was done both to improve our understanding of the typology and to ensure we had a large enough set of labeled examples to perform an informative analysis. Subsequently, we annotated the rest in the same manner, annotating individually and then agreeing on a unified ground truth as a group afterwards. Our total number of verified reduplications in the Salad-Salad corpus was 280.</p>
</section>
<section id="opensubtitles" class="level3">
<h3 class="anchored" data-anchor-id="opensubtitles">OpenSubtitles</h3>
<p>Our list of 613 samples, while filtered for examples that fit a pattern of reduplication, contained a significant amoun of non-CR data. An example of this is repetition that was not reduplication, such as the use of the phrase “now I’m a black widow widow” in <em>A Bug’s Life</em> (the first “widow” is part of “black widow”, the type of spider, and the second is the normal usage of “widow”). To address this, we added the label N to our annotations to indicate that an example was not an instance of CR. By including the surrounding context of each example, we were able to more easily judge whether a repetition was meaningful CR or not. We split the samples into the first 200 entries and the remaining 413 and annotated the sets as was done with the Salad-Salad corpus, with meetings after annotating each set to resolve any disagreements.</p>
</section>
<section id="agreement" class="level3">
<h3 class="anchored" data-anchor-id="agreement">Agreement</h3>
<p>Using the <code>krippendorff</code> python package (Castro, 2017), we calculated Krippendorff’s Alpha values to see how well we agreed on these labels for each set (we used a few N/U annotations for Non-RC/Unclear for the Salad-Salad dataset, but we treat such labels as missing annotations for the purposes of calculating Krippendorff’s Alpha). The results are as follows:</p>
<ul>
<li>Salad-Salad:
<ul>
<li>Examples 1-100: 0.2132</li>
<li>Examples 101-286: 0.5204</li>
</ul></li>
<li>OpenSubtitles:
<ul>
<li>Examples 1-200: 0.6873</li>
<li>Examples 201-613: 0.5542</li>
</ul></li>
</ul>
<p>Overall, this agreement was relatively week, as social scientists typically discard data with an alpha value below 0.667. However, we were able to come to a consensus on the majority of our annotations, and the disagreements we had were typically over edge cases or examples that were difficult to classify. Thus, while we acknowledge that our agreement was not perfect, we believe that our annotations are still valid and can be used for tentative analysis.</p>
</section>
</section>
<section id="word-length-frequency" class="level2">
<h2 class="anchored" data-anchor-id="word-length-frequency">3.3 Word Length &amp; Frequency</h2>
<p>In addition to the above processing, we will include in our analysis in the next section some discussion of word length and word frequency as potentially influential factors in our results. This is partially derived from the acknowledgement that POS may not exclusively have a part to play in the semantic contribution of reduplication (for instance, a word’s frequency may impact whether or not it can be understood with a prototypical versus salient interpretation), and are interested in substantiating more strongly the specific link between POS and semantic contribution, should there be one. Word length could be calculated straightforwardly in R.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>salad <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/salad_consolidated_refined.csv"</span>)      <span class="co"># Reading the File</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>salad<span class="sc">$</span>Length <span class="ot">&lt;-</span> <span class="fu">nchar</span>(salad<span class="sc">$</span>Word)      <span class="co"># Creating a Length Column</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>freq_list <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/unigram_freq.csv"</span>)     <span class="co"># Reading the Frequency Counter File</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>freq_list<span class="sc">$</span>Word <span class="ot">&lt;-</span> freq_list<span class="sc">$</span>word              <span class="co"># Making it so that both tables have a "Word" column</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>freq_list <span class="ot">&lt;-</span> freq_list[, <span class="sc">-</span><span class="dv">1</span>]                  <span class="co"># Preventing the "word" column from sticking around</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>salad_counts <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(salad, freq_list, <span class="at">by=</span><span class="st">"Word"</span>)               <span class="co"># Adding the frequency list to the main tibble</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>full_222k <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"../data/en_v1_222k/en_v1_222k_full.csv"</span>, <span class="at">delim=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)          <span class="co"># Reading the File, adjusting for it being .csv</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>full_222k<span class="sc">$</span>Length <span class="ot">&lt;-</span> <span class="fu">nchar</span>(full_222k<span class="sc">$</span>Word)                           <span class="co"># Doing the Character Counts</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>full_222k_counts <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(full_222k, freq_list, <span class="at">by=</span><span class="st">"Word"</span>)     <span class="co"># Doing Freqs</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(full_222k_counts, <span class="st">"../data/en_v1_222k/full_222k_counted.csv"</span>)                <span class="co"># Writing the File</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Our calculations for word frequency are based on a <a href="https://www.kaggle.com/datasets/rtatman/english-word-frequency">dataset</a> of the top 333,333 most frequent English words as they appear in the Google Web Trillion Word Corpus. To normalize the values, the log of the frequency was taken.</p>
</section>
</section>
<section id="analysis-discussion" class="level1">
<h1>4.0 Analysis &amp; Discussion</h1>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">4.1 Findings</h2>
<p>As mentioned in the previous section, we annotated both the Salad-Salad and OpenSubtitles datasets. Although Salad-Salad’s contents were all determined to be CR, as became apparent during the annotating phase, the vast majority of the examples in our OpenSubtitles subset were still not true CR even after several rounds of filtering. The following pie chart illustrates the percentages of different labels, with ‘N’ representing ‘not CR.’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>salad.data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/salad_consolidated_refined_counted.csv"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>opensubs.data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/en_v1_222k/full_222k_counted.csv"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>opensubs.filtered <span class="ot">&lt;-</span> <span class="fu">subset</span>(opensubs.data, Label <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"P"</span>, <span class="st">"E"</span>, <span class="st">"S"</span>))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>opensubs.selected <span class="ot">&lt;-</span> opensubs.filtered[, <span class="fu">names</span>(opensubs.filtered) <span class="sc">%in%</span> <span class="fu">names</span>(salad.data)]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>combined.data <span class="ot">&lt;-</span> <span class="fu">rbind</span>(salad.data, opensubs.selected)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(combined.data, <span class="st">"../data/combined_opensubs_salad_data.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>combined.data<span class="sc">$</span>Log_Freq_Count <span class="ot">&lt;-</span> <span class="fu">log</span>(combined.data<span class="sc">$</span>Freq_Count)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Word Label POS Word_Length Freq_Count Log_Freq_Count
1       adam     S  NN           4   21694386       16.89256
2 aggressive     P  JJ          10    7345918       15.80966
3 aggressive     P  JJ          10    7345918       15.80966
4      alone     E  JJ           5   39326417       17.48741
5    amherst     P  NN           7    2846723       14.86168
6   anywhere     E  RB           8   23947583       16.99138</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>labels<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">readLines</span>(<span class="st">"../data/annotations/opensubs_agreed_1.txt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines("../data/annotations/opensubs_agreed_1.txt"): incomplete
final line found on '../data/annotations/opensubs_agreed_1.txt'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>labels<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">readLines</span>(<span class="st">"../data/annotations/opensubs_agreed_2.txt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines("../data/annotations/opensubs_agreed_2.txt"): incomplete
final line found on '../data/annotations/opensubs_agreed_2.txt'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>all.labels <span class="ot">&lt;-</span> <span class="fu">c</span>(labels<span class="fl">.1</span>, labels<span class="fl">.2</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>label.freq <span class="ot">&lt;-</span> <span class="fu">table</span>(all.labels)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>label.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Label =</span> <span class="fu">names</span>(label.freq), <span class="at">Frequency =</span> <span class="fu">as.numeric</span>(label.freq))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>label.df<span class="sc">$</span>Percentage <span class="ot">&lt;-</span> label.df<span class="sc">$</span>Frequency <span class="sc">/</span> <span class="fu">sum</span>(label.df<span class="sc">$</span>Frequency) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(label.df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Frequency, <span class="at">fill =</span> Label)) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="st">"y"</span>, <span class="at">start =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Semantic Contribution Labels in OpenSubs Dataset"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Label"</span>) <span class="sc">+</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">paste</span>(label.df<span class="sc">$</span>Label, <span class="fu">sprintf</span>(<span class="st">"(%0.1f%%)"</span>, label.df<span class="sc">$</span>Percentage))) <span class="sc">+</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Thus, we decided to select only the positive CR examples from the OpenSubtitles dataset and append these annotated examples to the Salad-Salad dataset and perform statistical analysis on this combined dataset. First, we looked at the distributions of both POS and Semantic Contribution Labels to get a sense of the makeup of our dataset, as seen in the following bar graphs. Nouns were by far the most common POS to be contrastively reduplicated, and the most common semantic contribution assigned across the board was the prototypical label.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined.data, <span class="fu">aes</span>(<span class="at">x =</span> POS, <span class="at">fill =</span> POS)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span> <span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Parts of Speech"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Part of Speech"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined.data, <span class="fu">aes</span>(<span class="at">x =</span> Label, <span class="at">fill =</span> Label)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span> <span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Semantic Contributions"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Semantic Contribution"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking at the stacked graph below, we can see certain trends beginning to surface. Although prototypical labels still make up a large percentage of the examples for each POS, there is a more even split between prototypical and extreme readings for adjectives, and prototypical and salient readings for adverbs. The exact percentages of semantic contribution by POS is given in the table below the graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(combined.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Word              Label               POS             Word_Length    
 Length:294         Length:294         Length:294         Min.   : 2.000  
 Class :character   Class :character   Class :character   1st Qu.: 4.000  
 Mode  :character   Mode  :character   Mode  :character   Median : 5.000  
                                                          Mean   : 5.194  
                                                          3rd Qu.: 6.000  
                                                          Max.   :13.000  
   Freq_Count        Log_Freq_Count 
 Min.   :2.957e+05   Min.   :12.60  
 1st Qu.:2.173e+07   1st Qu.:16.89  
 Median :4.965e+07   Median :17.72  
 Mean   :1.430e+08   Mean   :17.70  
 3rd Qu.:1.447e+08   3rd Qu.:18.79  
 Max.   :2.399e+09   Max.   :21.60  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined.data, <span class="fu">aes</span>(<span class="at">x =</span> POS, <span class="at">fill =</span> Label)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Semantic Contributions by POS"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"POS"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>label.counts <span class="ot">&lt;-</span> combined.data <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(POS, Label) <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'POS'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pos.totals <span class="ot">&lt;-</span> combined.data <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(POS) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total.count =</span> <span class="fu">n</span>())</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>label.percentages <span class="ot">&lt;-</span> label.counts <span class="sc">%&gt;%</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pos.totals, <span class="at">by =</span> <span class="st">"POS"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> (count <span class="sc">/</span> total.count) <span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>label.percentages.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(label.percentages)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(label.percentages.df, <span class="at">caption =</span> <span class="st">"Percentage of Semantic Contributions by POS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Percentage of Semantic Contributions by POS</caption>
<thead>
<tr class="header">
<th style="text-align: left;">POS</th>
<th style="text-align: left;">Label</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">total.count</th>
<th style="text-align: right;">percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">JJ</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">44.444444</td>
</tr>
<tr class="even">
<td style="text-align: left;">JJ</td>
<td style="text-align: left;">P</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">48.611111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JJ</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">6.944444</td>
</tr>
<tr class="even">
<td style="text-align: left;">NN</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">8.441558</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NN</td>
<td style="text-align: left;">P</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">69.480519</td>
</tr>
<tr class="even">
<td style="text-align: left;">NN</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">22.077922</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RB</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">21.875000</td>
</tr>
<tr class="even">
<td style="text-align: left;">RB</td>
<td style="text-align: left;">P</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">37.500000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RB</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">40.625000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VB</td>
<td style="text-align: left;">E</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">16.666667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VB</td>
<td style="text-align: left;">P</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">58.333333</td>
</tr>
<tr class="even">
<td style="text-align: left;">VB</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">25.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The regression model we ran on the dataset formalized these trends, as discussed in the next section.</p>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">4.2 Analysis</h2>
<p>We ran a multinomial logistic regression model on our dataset, as our output variable (semantic contribution) was categorical. We ran a total of three models, each looking at a different set of predictor variables. The first model takes POS, word length, and log word frequency into account. The summary results of this model are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>combined.data<span class="sc">$</span>POS <span class="ot">&lt;-</span> <span class="fu">factor</span>(combined.data<span class="sc">$</span>POS, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"NN"</span>, <span class="st">"JJ"</span>, <span class="st">"RB"</span>, <span class="st">"VB"</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>combined.data<span class="sc">$</span>Label <span class="ot">&lt;-</span> <span class="fu">factor</span>(combined.data<span class="sc">$</span>Label, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"P"</span>, <span class="st">"S"</span>, <span class="st">"E"</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>combined.data<span class="sc">$</span>POS <span class="ot">&lt;-</span> <span class="fu">relevel</span>(combined.data<span class="sc">$</span>POS, <span class="at">ref =</span> <span class="st">"NN"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>combined.data<span class="sc">$</span>Label <span class="ot">&lt;-</span> <span class="fu">relevel</span>(combined.data<span class="sc">$</span>Label, <span class="at">ref =</span> <span class="st">"P"</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Label <span class="sc">~</span> POS <span class="sc">+</span> Word_Length <span class="sc">+</span> Log_Freq_Count, <span class="at">data =</span> combined.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  21 (12 variable)
initial  value 322.992013 
iter  10 value 253.237645
iter  20 value 252.191106
iter  20 value 252.191105
iter  20 value 252.191105
final  value 252.191105 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Label ~ POS + Word_Length + Log_Freq_Count, 
    data = combined.data)

Coefficients:
  (Intercept)      POSJJ    POSRB     POSVB Word_Length Log_Freq_Count
S   0.1250445 -0.8024024 1.419712 0.2926930  0.08383826    -0.09731712
E  -0.2866130  2.0088020 1.857399 0.8456115  0.14719448    -0.14900778

Std. Errors:
  (Intercept)     POSJJ     POSRB     POSVB Word_Length Log_Freq_Count
S    2.028345 0.5185374 0.4982946 0.4471255  0.08877777      0.1058542
E    2.321282 0.3873713 0.6164822 0.5536555  0.09413582      0.1206399

Residual Deviance: 504.3822 
AIC: 528.3822 </code></pre>
</div>
</div>
<p>As the distributions showed that nouns and prototypical were the most common in their respective variables, we used these categories as our baselines when calculating the log odds in the model.</p>
<p>The results can be interpreted as follows:</p>
<ul>
<li>The log odds of having a salient reading rather than a prototypical reading:
<ul>
<li>decreases by 0.80 as you switch from noun to adjective.</li>
<li>increases by 1.42 as you switch from noun to adverb.</li>
<li>increases by 0.29 as you switch from noun to verb. (not significant result)</li>
<li>increases by 0.084 for every 1 letter increase in word length. (not significant result)</li>
<li>decreases by 0.097 for every 1 unit increase in log frequency. (not significant result)</li>
</ul></li>
<li>The log odds of having an extreme reading rather than a prototypical reading:
<ul>
<li>increases by 2.01 as you switch from noun to adjective.</li>
<li>increases by 1.86 as you switch from noun to adverb.</li>
<li>increases by 0.85 as you switch from noun to verb. (not significant result)</li>
<li>increases by 0.147 for every 1 letter increase in word length. (not significant result)</li>
<li>decreases by 0.149 for every 1 unit increase in log frequency. (not significant result)</li>
</ul></li>
</ul>
<p>The significance of the coefficient results was determined by running a 2-tailed z test, and the resulting z and p scores are given below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients<span class="sc">/</span><span class="fu">summary</span>(model)<span class="sc">$</span>standard.errors</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)     POSJJ    POSRB     POSVB Word_Length Log_Freq_Count
S  0.06164851 -1.547434 2.849142 0.6546104    0.944361     -0.9193509
E -0.12347188  5.185728 3.012900 1.5273242    1.563639     -1.2351447</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z), <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)        POSJJ       POSRB     POSVB Word_Length Log_Freq_Count
S   0.9508427 1.217586e-01 0.004383735 0.5127186   0.3449852      0.3579121
E   0.9017334 2.151730e-07 0.002587638 0.1266804   0.1179023      0.2167767</code></pre>
</div>
</div>
<p>Using a 0.05 threshold, we can see that the log odd differences for noun to verb, word length, and log frequency are not significant. For the case of noun to verb, this result makes sense as the original distributions also show that these two categories show a similar split between the three semantic categories. For the continuous variables, although the trends might not be significant, and a larger dataset might disprove trends observed here, we still ran models on just these variables to get a sense of the overall trends. The results of the word length model are plotted below. Based on the coefficients calculated by the model, the graph plotted the predicted likelihood of being assigned a particular semantic contribution label given word length.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>length.model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Label <span class="sc">~</span> Word_Length, <span class="at">data =</span> combined.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 322.992013 
iter  10 value 277.820475
final  value 277.820469 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(length.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Label ~ Word_Length, data = combined.data)

Coefficients:
  (Intercept) Word_Length
S   -1.587050   0.1035639
E   -2.158591   0.1986573

Std. Errors:
  (Intercept) Word_Length
S   0.4656235  0.08452959
E   0.4734252  0.08237858

Residual Deviance: 555.6409 
AIC: 563.6409 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Word_Length =</span> <span class="fu">seq</span>(<span class="fu">min</span>(combined.data<span class="sc">$</span>Word_Length), <span class="fu">max</span>(combined.data<span class="sc">$</span>Word_Length), <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>length.predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(length.model, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>length.predictions.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(new.data, length.predictions)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>length.predictions.df <span class="ot">&lt;-</span> <span class="fu">gather</span>(length.predictions.df, Label, Probability, <span class="sc">-</span>Word_Length)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(length.predictions.df, <span class="fu">aes</span>(<span class="at">x =</span> Word_Length, <span class="at">y =</span> Probability, <span class="at">color =</span> Label)) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Likelihood of Semantic Contribution Label by Word Length"</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Word Length"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability"</span>,</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Semantic Contribution Label"</span>) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As word length increases, the probability of getting a prototypical reading decreases, while the probability of getting an extreme reading increases. There is also a slight increase in the salient category, but this is a much slighter trend than seen in the other two. Initial explanations for why these trends could have arisen are discussed in the next section. Similarly, we ran a model with log frequency as the predicting variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>freq.model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Label <span class="sc">~</span> Log_Freq_Count, <span class="at">data =</span> combined.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 322.992013 
final  value 280.015169 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(freq.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Label ~ Log_Freq_Count, data = combined.data)

Coefficients:
  (Intercept) Log_Freq_Count
S  -1.0582332   0.0002438423
E   0.9773974  -0.1182008828

Std. Errors:
  (Intercept) Log_Freq_Count
S    1.670483     0.09366132
E    1.649430     0.09365141

Residual Deviance: 560.0303 
AIC: 568.0303 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Log_Freq_Count =</span> <span class="fu">seq</span>(<span class="fu">min</span>(combined.data<span class="sc">$</span>Log_Freq_Count), <span class="fu">max</span>(combined.data<span class="sc">$</span>Log_Freq_Count), <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>freq.predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(freq.model, <span class="at">newdata =</span> new_data, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>freq.predictions.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(new_data, freq.predictions)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>freq.predictions.df <span class="ot">&lt;-</span> <span class="fu">gather</span>(freq.predictions.df, Label, Probability, <span class="sc">-</span>Log_Freq_Count)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(freq.predictions.df, <span class="fu">aes</span>(<span class="at">x =</span> Log_Freq_Count, <span class="at">y =</span> Probability, <span class="at">color =</span> Label)) <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Likelihood of Semantic Contribution Label by Frequency"</span>,</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Log Normalized Frequency"</span>,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability"</span>,</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Semantic Contribution Label"</span>) <span class="sc">+</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ReduplicationProjectWriteup_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This model also revealed some general trends. Namely, prototypical readings (and to a lesser extent, salient readings) increased as frequency increased, while extreme readings decreased as frequency increased. In case the trends seen in these graphs were a result of POS being a confounding variable influencing word length or frequency (e.g., if adjectives in our dataset were longer or less frequent overall than other POS, trends seen in these models’ results could just be a result of POS and not the variable at hand), we calculated simple mean and median stats for word length and frequency by POS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>avg.stats <span class="ot">&lt;-</span> combined.data <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(POS) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg.word.length =</span> <span class="fu">mean</span>(Word_Length),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">median.word.length =</span> <span class="fu">median</span>(Word_Length),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg.log.frequency =</span> <span class="fu">mean</span>(Log_Freq_Count),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">median.log.frequency =</span> <span class="fu">median</span>(Log_Freq_Count))</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(avg.stats, <span class="at">format =</span> <span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 23%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">POS</th>
<th style="text-align: right;">avg.word.length</th>
<th style="text-align: right;">median.word.length</th>
<th style="text-align: right;">avg.log.frequency</th>
<th style="text-align: right;">median.log.frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NN</td>
<td style="text-align: right;">5.110390</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">17.52901</td>
<td style="text-align: right;">17.62851</td>
</tr>
<tr class="even">
<td style="text-align: left;">JJ</td>
<td style="text-align: right;">5.402778</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">17.48912</td>
<td style="text-align: right;">17.69468</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RB</td>
<td style="text-align: right;">5.281250</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">19.41297</td>
<td style="text-align: right;">19.94505</td>
</tr>
<tr class="even">
<td style="text-align: left;">VB</td>
<td style="text-align: right;">5.055556</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">17.35916</td>
<td style="text-align: right;">17.05917</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These stats show that across the different parts of speech, the word length and frequency were roughly the same (the only notable divergence is adverbs being slightly more frequent on average), and so we can conclude that the trends observed in the word length and frequency models are a result of those variables directly and not an underlying POS effect.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">4.3 Discussion</h2>
<p>Thus, based on the models and the various trends and results, we can conclude that POS does have a statistically significant impact on the semantic contribution of contrastive reduplication. Meanwhile, word length and frequency also seem to correlate to certain trends in semantic contribution of CR, but based on our data, these trends are not statistically significant.</p>
<p>There were many trends relating to parts of speech. First, nouns are most likely out of the parts of speech to get prototypical readings, as we expected. Verbs are similar to nouns in their overall distribution of semantic contributions, with the highest portion of them having prototypical readings. Adjectives, on the other hand, are more likely to get extreme readings than other parts of speech (a trend which we had also anticipated). Finally, adverbs are most likely out of the parts of speech to get salient readings, and get them more often than other readings. These trends have several potential explanations. For instance, as supported by our annotating experiences as well, it was much easier to conceptualize a prototypical definition for nouns and verbs than it was for modifiers. For example, it is difficult to describe a prototypical definition for the adjective “favorite,” and indeed, both examples of this word got an extreme reading. Building off of this, as adjectives can have a scalar nature, they lend themselves well to extreme CR readings. Finally, in our dataset, indexicals such as “here” were classed as adverbs, and as indexicals require context to resolve their meanings, we believe this is a reason why adverbs got the salient reading most often.</p>
<p>The trends in the word length and frequency results were described in the previous section, and they also have preliminary explanations. The decrease in prototypical readings as word length increases makes sense, as longer words are likely less frequent and thus have less readily accessible prototypical versions. This is confirmed by the frequency model’s results, as prototypical readings increase as frequency increases. Extreme readings, on the other hand, increase with word length, and this corresponds to its decrease as frequency increases. Why exactly longer or less frequent words tend to get extreme readings is not immediately clear. As mentioned above, since there is no influence of POS on the average length or frequency of any given word, we cannot assume this trend in the extreme readings is correlated with adjectives and their length/frequency. Since adjectives have this tendency for getting extreme readings, we had predicted that this could be a factor in the trend for extreme readings, but since this might not be the case, an explanation for this trend is left for future research. Finally, though there is a slight slope in the lines for salient readings, it is overall much more stable than the other factors. This could be because given a rich enough discourse context, any word can take on a salient CR meaning, and thus the likelihood of getting this reading is not influenced by word length or frequency. However, it is worth noting that as mentioned above, the word length and frequency results were not statistically significant according to our dataset. Thus, further research on a larger dataset might confirm or deny the significance of these trends.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">4.4 Limitations</h2>
<p>There are, of course, aspects of the research we have described here which could be improved through further investigation or a reworking of our methodological process. A particular factor that limits the extent of our findings is that some of the entries in the Salad-Salad Corpus are drawn from written sources, and as acknowledged in Widlitzki (2016), the informal register of reduplication as a whole can be a biasing influence on what is written versus spoken when it comes to this linguistic phenomenon. Our data is not exclusively spoken language, and thus may be somewhat skewed relative to a data that is entirely based on transcribed utterances.</p>
<p>A major caveat to our findings is that our typology was fleshed out both using examples from our dataset, and overall was designed by the three of us in anticipation of annotating the rest of our data, resulting in us having some theory as to how our annotations ‘should’ align with our data when we did sit down and begin sorting. For example, it is possible that our classification of many adjectives as Extreme may have been to some degree influenced by our expectation that this would be the case upon aggregating our annotated data. There is certainly some bias in our research as a result of us acting as both annotators and analysts.</p>
<p>We would also like to acknowledge that the typology that we constructed at the outset, though deliberated and agreed upon between the three of us, could be fundamentally flawed on a theoretical level; there could be categories missing whose presence would create a better model for the trends that we observe, for instance. Moreover, our low agreement levels suggest that this typology may not be very well-defined, and so we might wish to refine these categories before performing any follow-up research. There are also other typologies of CR not based on a P/E/S paradigm of semantic contribution, such as the scale of conventionalization of meaning discussed in Section 1 that was proposed in Widlitzki (2016), that may be more illuminating with regards to the reason for variation within CR.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>5.0 Conclusion</h1>
<p>Based on our dataset, a few statistically significant trends between POS and semantic contribution of reduplication have been identified. Additionally, some trends between word length/frequency and semantic contribution have also been observed, but more research into the strength of these trends is needed. Supplemental data from a larger corpus can provide more evidence to confirm or challenge these trends, and potentially bring to light new insights regarding the nature of contrastive reduplication.</p>
</section>
<section id="citations" class="level1">
<h1>Citations</h1>
<p>Castro, S. (2017). <em><a href="https://pypi.org/project/krippendorff/#description">Fast Krippendorff: Fast computation of Krippendorff’s alpha agreement measure</a></em>.</p>
<p>P. Lison and J. Tiedemann, 2016, <a href="http://www.lrec-conf.org/proceedings/lrec2016/pdf/947_Paper.pdf">OpenSubtitles2016: Extracting Large Parallel Corpora from Movie and TV Subtitles</a>. In Proceedings of the 10th International Conference on Language Resources and Evaluation (LREC 2016)</p>
<p>Ghomeshi, Jila &amp; Jackendoff, Ray &amp; Rosen, Nicole &amp; Russell, Kevin. (2004). <em>Contrastive Focus Reduplication in English (The Salad-Salad Paper)</em>. Natural Language and Linguistic Theory. 22. 307-357. 10.1023/B:NALA.0000015789.98638.f9.</p>
<p>Bianca, Widlitzki. (2016). <em>Talk talk, not just small talk. Exploring English contrastive focus reduplication with the help of corpora</em>. ICAME Journal. 40. 10.1515/icame-2016-0008.</p>
<p>Inkelas, Sharon &amp; Downing, Laura. (2015). <em>What is Reduplication? Typology and Analysis Part 1/2: The Typology of Reduplication. Language and Linguistics Compass</em>. 9. 502-515. 10.1111/lnc3.12166.</p>
<p>Harada, Ryuji. (2007). <em>A Note on Language Typology by the Status of Reduplication</em>. CORE. oai:otsuma.repo.nii.ac.jp:00001776</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>